[automount]
enabled=false
mountFsTab=false

[interop]
enabled=false
appendWindowsPath=false

[network]
generateHosts=true
generateResolvConf=true
hostname=node-a

[user]
default=observer

[boot]
systemd=true
